# -*- coding: utf-8 -*-
"""DS_C2_SC2_SamariaEdithLópezNegrete.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15769FkEiDqUZNQObKI7FgeY9OvgAmstY

a.-Se lee el archivo que se encuentra en la siguiente liga
"""

import pandas as pd
vaccinations = pd.read_csv("/content/drive/MyDrive/country_vaccinations.csv")
vaccinations

"""b. Mostrar la estructura y tipos de datos de cada columna para identificar qué operaciones puedes realizar con cada una de ellas, asegurándote que las columnas con fechas sean del tipo datetime64."""

vaccinations["date"] = pd.to_datetime(vaccinations["date"])
vaccinations.info()

"""c. Determinar la cantidad de vacunas aplicadas de cada compañía (con base en cómo lo reporta cada país en la columna vaccines, en otras palabras, agrupe por vaccines y realice la sumatoria)."""

vaccinations[['vaccines', 'total_vaccinations']].groupby('vaccines').sum()

"""d. Obtener la cantidad de vacunas aplicadas en todo el mundo."""

vacunas_totales = vaccinations["total_vaccinations"].sum()
print("Total de vacunas aplicadas en todo el mundo:",vacunas_totales)

"""e. Calcular el promedio de vacunas aplicadas por país."""

promedio_pais = vaccinations.groupby ("country")["total_vaccinations"].mean()
print("El promedio de vacunas por pais es:", promedio_pais)

"""f. Determinar la cantidad de vacunas aplicadas el día 29/01/21 en todo el mundo."""

vacunas_aplicadas_29_01_21 = vaccinations[vaccinations["date"] == "2021-01-29"]
vacunas_aplicadas_29_01_21_total = vacunas_aplicadas_29_01_21["total_vaccinations"].sum()
print("El total de las vacunas aplicadas el dia 29-01-2021 en el mundo fue de: ", vacunas_aplicadas_29_01_21_total)

"""g. Crear un dataframe nuevo denominado conDiferencias que contenga los datos originales y una columna derivada (diferencias) con las diferencias de aplicación entre las columnas daily_vaccionations y daily_vaccionations_raw.  """

vaccinations['diferencias'] = vaccinations['daily_vaccinations'] - vaccinations['daily_vaccinations_raw']
conDiferencias = vaccinations.copy()
print(conDiferencias)

"""h. Obtener el periodo de tiempo entre el registro con fecha más reciente y el registro con fecha más antigua."""

fecha_mas_reciente = vaccinations["date"].max()
fecha_mas_antigua = vaccinations["date"].min()
diferencia_fechas = pd.to_datetime(fecha_mas_reciente) - pd.to_datetime(fecha_mas_antigua)
print("Dia del registro con fecha más reciente:", vaccinations["date"].min())
print("Dia del registro con fecha más antigua:", vaccinations["date"].max())
print("Diferencia entre fechas:",diferencia_fechas)

"""i. Crear un dataframe nuevo denominado conCantidad que contenga los datos originales y una columna derivada (canVac) con la cantidad de vacunas utilizadas cada día (usar la columna vaccines y separar por el carácter , )."""

vaccinations["canVac"] = vaccinations["vaccines"].str.split(",")
vaccinations["canVac"] = vaccinations["canVac"].apply(len)
conCantidad = vaccinations[["date", "country", "total_vaccinations", "vaccines", "canVac"]]
conCantidad.head()

"""j. Generar un dataframe denominado antes20 con todos los registros que se hayan realizado antes del 20 de diciembre de 2020."""

antes20_12_20 = vaccinations.loc[vaccinations["date"] < "2020-12-20"]
antes20_12_20.head()

"""k. Obtener un dataframe denominado pfizer con todos los registros donde se haya utilizado la vacuna Pfizer."""

pfizer = vaccinations.loc[vaccinations["vaccines"].str.contains("Pfizer")]
pfizer.head()

"""l. Almacenar los dataframes generados (conDiferencias, conCantidad, antes20 y pfizer) en un archivo de Excel denominado resultadosReto.xlsx, donde cada dataframe ocupe una hoja diferente. Se recomienda ver la documentación de pd.ExcelWriter."""

with pd.ExcelWriter('/content/resultadosReto.xlsx')as writer :
    conDiferencias.to_excel(writer, sheet_name = "conDiferencias")
    conCantidad.to_excel(writer, sheet_name = "conCantidad")
    antes20_12_20.to_excel(writer, sheet_name = "antes20")
    pfizer.to_excel(writer, sheet_name = "pfizer")
print("Los resultados se han guardado exitosamente en resultadosReto.xlsx")